# Generated by Django 4.2.5 on 2023-09-18 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 1, 2, 44, 717715, tzinfo=datetime.timezone.utc)),
        ),
    ]
