# Generated by Django 4.2.5 on 2023-09-18 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 1, 21, 21, 215227, tzinfo=datetime.timezone.utc)),
        ),
    ]
